version: "2.1"
services:
  drupal:
    build: 
      context: .
      dockerfile: drupal.DockerFile      
    
    volumes: 
      - drupal-modules:/var/www/html/modules \
      - drupal-profiles:/var/www/html/profiles \
      - drupal-sites:/var/www/html/sites \
      - drupal-themes:/var/www/html/themes \

    ports:
      - '80:80'
  postgres:
    image: postgres

    environment: 
      - POSTGRES_PASSWORD=mypasswd
    volumes: 
      - drupal-data:/var/lib/postgresql/data
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
