apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    type: test-deployment
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        tier: frontend
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.18-asdas
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
